print("Welcome to the brand name generator~~")
username=input("Hello~ My name is Andy! What is your name?\n")
print("Hello ",username,"!", "\nNice to meet you!")
username_city=input("Which city did you grow up in?\n")
print(username_city,"Huh...","\nI might have been there sometimes ago." )
answer1=input("Did you know that?\n")
print(answer1,"Alright, but I don't remember when anyway.","\nhahaha!")
username_pet=input("What is your pet's name?\n")
print(username_pet,","," Wow~~ \nIt's such a cute name for your pet.","\nI like it!")
answer2=input("You know what?\n")
print(answer2)
answer3=input("I have an idea!\n")
print(answer3)
print("your brand name could be: " + username_city + " " + username_pet + ".")
answer4=input("Doesn't it sound good?\n")
print("You welcome, if you like it.","\nIf you don't like it, what sahould your brand name be?")
answer5=input("Do you have any magical idea?\n")
print(answer5,"~" "Good idea! That should be your brand name.")
