print("Welcome to the brand name generator~~")
username=input("Hello~ My name is Andy! What is your name?\n")
print("Hello ",username,"!")
username_city=input("Which city did you grow up in?\n")
print(username_city,"Huh...","\nI might have been there sometimes ago" )
input("Did you know tha?\n")
print("Yes, but I don't remember when","\nhahaha!")
username_pet=input("What is your pet's name\n")
print(username_pet,","," Wow~~ \nIt's such a cute name for your pet","\nI like it!")
print(input("You know what?\n"))
print(input("I have an idea!\n"))
print("your brand name could be: " + username_city + " " + username_pet)
answer=input("Doesn't it sound good?\n")
print(answer)
